apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app2-deployment
  labels:
    app: my-app2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app2

  template:
    metadata:
      name: my-app2
      labels:
        app: my-app2
    spec:
      containers:
        - name: my-container
          image: us-central1-docker.pkg.dev/prod-project-424777/gke-cicd-repo/app2
          ports:
            - containerPort: 80
---            

apiVersion: v1 
kind: Service
metadata: 
  name: my-app2-lb-service
  labels:
    app: my-app2-lb-service

spec:
  type: LoadBalancer
  selector:
    app: my-app2
  ports:
    - name: http
      port: 80
      targetPort: 80 